export { default as CalendarPage } from './CalendarPage'
export { default as CommunityPage } from './CommunityPage'
export { default as DashboardPage } from './DashboardPage'
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as FAQsPage } from './FAQsPage'
export { default as RegisterPage } from './RegisterPage'
export { default as MyJournalPage } from './MyJournalPage'
export { default as LoadingPage } from './LoadingPage'

